"""empty message

Revision ID: 26d9f34d510b
Revises: f648841b28cd
Create Date: 2021-04-30 06:14:39.722100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d9f34d510b'
down_revision = 'f648841b28cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('img', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'img')
    # ### end Alembic commands ###
